inpackage: True
dir: "{{.InterfaceDir}}"
with-expecter: false
packages:
  pinman/internal/clients/generic:
    interfaces:
      ClientInterface: {}
      HttpDoer: {}
  pinman/internal/clients/pinballmap:
    interfaces:
      ClientInterface: {}
