inpackage: True
dir: "{{.InterfaceDir}}"
with-expecter: false
packages:
  pinman/internal/utils:
    interfaces:
      # select the interfaces you want mocked
      HttpDoer: {}
  pinman/internal/clients/pinballmap:
    interfaces:
      ClientInterface: {}
