version: "3.4"

services:
  pinman-node-dev:
    build:
      context: .
      target: node-dev
    image: alexstojda/pinman-development:${VERSION:-local}

  pinman-go-dev:
    depends_on:
      - postgres
    build:
      context: .
      target: go-dev
    image: alexstojda/pinman-development:${VERSION:-local}

  migrate-dev:
    depends_on:
      - postgres
    build:
      context: .
      target: go-dev
    command:
      - run-migrate
    env_file:
      - ./.env.local
    environment:
      - POSTGRES_HOST=postgres
    image: alexstojda/pinman-development:${VERSION:-local}

  pinman:
    build:
      context: .
      target: prod
    image: alexstojda/pinman:${VERSION:-local}
    environment:
      - NAME=value
    ports:
      - "8080"

  ## Code generation
  openapi-client:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./web/app/src/generated:/out
      - ./api:/api
    command:
    - generate
    - -i
    - /api/openapi.yaml
    - -g
    - typescript-axios
    - -o
    - /out

  ### Dependencies
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env.local
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
