version: "3.4"

services:
  pinman-node-dev:
    build:
      context: .
      target: node-dev
    image: alexstojda/pinman/node-dev:${VERSION:-local}

  pinman-go-dev:
    depends_on:
      - postgres
    build:
      context: .
      target: go-dev
    image: alexstojda/pinman/go-dev:${VERSION:-local}

  pinman:
    depends_on:
      - postgres
    build:
      context: .
      target: prod
      args:
        REACT_APP_API_HOST: http://localhost:8080
    env_file:
      - ./.env.local
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
    image: alexstojda/pinman:${VERSION:-local}

  ## Code generation
  openapi-server:
    build:
      context: .
      target: go-gen
    image: alexstojda/pinman/openapi-server:${VERSION:-local}
    entrypoint: "sleep"
    command:
      - infinity

  openapi-client:
    build:
      context: .
      target: node-gen
    image: alexstojda/pinman/openapi-client:${VERSION:-local}
    entrypoint: "sleep"
    command:
      - infinity

  ### Dependencies
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env.local
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
