[build]
builder = "dockerfile"
# Only deploy versioned changes
watchPatterns = ["CHANGELOG.md"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 200
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 2